# Generated by Django 3.1 on 2020-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200816_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='type',
            field=models.CharField(choices=[('Half', 'Half'), ('Full', 'Full'), ('Empty', 'Empty')], default=None, max_length=20),
        ),
    ]
